### ISSUE TITLE
Some recent work about topic mdoels

### ISSUE THREAD

**Issue by NTUDeft** [BoChenGroup/PyDPM#10]
I find some intereseting work published in recent top conference. Can your guys include these projects into this library for convience?

The work list:
Alleviating “Posterior Collapse” in Deep Topic Models via Policy Gradient", NeurIPS 2022 
HyperMiner: Topic Taxonomy Mining with Hyperbolic Embedding , NeurIPS 2022 
Knowledge-Aware Bayesian Deep Topic Model, NeurIPS2022

**Comment by chaojiewang94** [comment]
I have inlcudes these works in our library and recommand the orginal authors of these work to reimplement their work in our framework. 

The file link can be found https://github.com/BoChenGroup/PyDPM/tree/master/pydpm/example/Hybrid_GM

**Comment by chaojiewang94** [comment]
The issue has to be closed
