### ISSUE TITLE
Some questions about the diffusion model

### ISSUE THREAD

**Issue by ISPZ** [BoChenGroup/PyDPM#15]
I’m surprise to see that the Diffusion Model has been added to your repository of Bayesian models. But it is a little complicated to understand the code of Diffusion Model, is there any tutorial to guide me to generate images with the trained model. And It would be nice if there was an example.
Thanks

**Comment by chaojiewang94** [comment]
Thanks, we have added an example for diffusion model in https://github.com/BoChenGroup/PyDPM/tree/master/pydpm/example/Deep_Learning_PM/Denoising_Diffusion_Probabilistic_Model

**Comment by chaojiewang94** [comment]
solved
