### ISSUE TITLE
how to recompile this project?

### ISSUE THREAD

**Issue by schygu** [BoChenGroup/PyDPM#16]
There are some problems about the sampler. and I suspect that these errors are caused by the compiled files. I want to recompile those cuda file. so which files are needed for recompilation and how can I do that? tks : )

**Comment by Dustone-Mu** [comment]
Those files with .c/.cu suffix in the 'pydpm/sampler/_compact/' path need to be compiled. Those file will be compiled automatically when you run this project first time, but problems occur sometimes.
The command
`nvcc -Xcompiler -fPIC -shared -o "filename.so" "filename_linux.cu"`
or
`nvcc -o "filename.dll" --shared "filname_win.cu"`
will be work when you recompile them.

**Comment by schygu** [comment]
tks alot. that works

**Comment by chaojiewang94** [comment]
solved
