### ISSUE TITLE
Some additional suggestions about Normalizing Flow model

### ISSUE THREAD

**Issue by Lewislvs** [BoChenGroup/PyDPM#19]
I’m glad that this repository has collected many generative models, like the diffusion model, variational autoencoder, Generative Adversarial Networks and so on. But I didn’t find the flow-like model, would you like to add a model and demo of Normalizing Flow?
 
Thanks for your effort in building this repository of the generative model.

**Comment by xinyangATK** [comment]
Thanks for your suggestions. We have implemented the RealNVP, one of the flow-based models, for 2D data. You can find it in [nflow.py](https://github.com/BoChenGroup/PyDPM/blob/master/pydpm/model/deep_learning_pm/nflow.py) and easily use it according to [NFlow_Demo.py](https://github.com/BoChenGroup/PyDPM/blob/master/pydpm/example/Deep_Learning_PM/Normlizing_Flow/NFlow_Demo.py)
And we'll update more flow-based models in the future and support more types of dataset.

**Comment by chaojiewang94** [comment]
Thanks for feedback if you have further question
