### ISSUE TITLE
sampler_kernel_win.cu FileNotFoundError: Could not find module site-packages '...\pydpm\_sampler\_compact\sampler_kernel.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by wds2014** [BoChenGroup/PyDPM#2]
How to fix the error below?
 `ptxas fatal   : Unresolved extern function '_Z3powfi'` `Traceback (most recent call last):`
 `  File "<stdin>", line 1, in <module>`
 `File "D:\Anaconda3\envs\mmdet\lib\site-packages\pydpm\_model\_pgbn.py", line 52, in __init__`
 ` self._sampler = Basic_Sampler(self._model_setting.device)` `File "D:\Anaconda3\envs\mmdet\lib\site-packages\pydpm\_sampler\_basic_sampler.py", line 37, in __init__` `self._gpu_sampler_initial()`
 `File "D:\Anaconda3\envs\mmdet\lib\site-packages\pydpm\_sampler\_basic_sampler.py", line 63, in _gpu_sampler_initial` 
`sampler = distribution_sampler_gpu(self.system_type)`
 `  File "D:\Anaconda3\envs\mmdet\lib\site-packages\pydpm\_sampler\_distribution_sampler_gpu.py", line 56, in __init__` 
`dll = ctypes.cdll.LoadLibrary(compact_path)` 
` File "D:\Anaconda3\envs\mmdet\lib\ctypes\__init__.py", line 451, in LoadLibrary`
 ` return self._dlltype(name)` ` File "D:\Anaconda3\envs\mmdet\lib\ctypes\__init__.py", line 373, in __init__`
 ` self._handle = _dlopen(self._name, mode)`
 `FileNotFoundError: Could not find module 'D:\Anaconda3\envs\mmdet\lib\site-packages\pydpm\_sampler\_compact\sampler_kernel.dll' (or one of its dependencies). Try using the full path with constructor syntax.` 

when running
 `from pydpm._model import PGBN`
 `model = PGBN([128,64,32], device='gpu') `
 Thanks.

**Comment by chaojiewang94** [comment]
@wds2014 You can try the latest version released on Github that can automatically detect the path of nvcc and no longer rely on the Pycuda library.  If  you have other problems about installation, please contact us, thx.

**Comment by chaojiewang94** [comment]
This issue has been solved. Welcome for the further questions.
