### ISSUE TITLE
Comparison of sampler built in this project and cupy

### ISSUE THREAD

**Issue by TJUZ** [BoChenGroup/PyDPM#20]
I found that the sampler part in this project is similar to cupy(cuda version of numpy). So what the difference between them? Does this pydpm sampler faster? btw, appreciate for your contribution in DTM

**Comment by Dustone-Mu** [comment]
CuPy is the parallel version for numpy based on CUDA. so the essence of CuPy and our sampler are similar. but there are some differences between them. Distribution sampler built in our project is easier to install, and thanks for the special optimization, this sampler is faster than CuPy. The more detailed comparison between them whill be released soon. stay tuned for this.

**Comment by Dustone-Mu** [comment]
Comparison between them was updated in _readme_

**Comment by chaojiewang94** [comment]
solved
