### ISSUE TITLE
/bin/sh: 1: nvcc: not found

### ISSUE THREAD

**Issue by qinhao87** [BoChenGroup/PyDPM#24]
I got an error when I run the sampler in my ubuntu PC:
'''
/bin/sh: 1: nvcc: not found
File "/PyDPM4.0.1/pydpm/sampler/distribution_sampler_gpu.py", line 99, in __init__
dll = ctypes.cdll.LoadLibrary(compact_path)
  File "/anaconda3/envs/pydpm/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "anaconda3/envs/pydpm/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError:/PyDPM4.0.1/pydpm/sampler/_compact/distribution_sampler.so: cannot open shared object file: No such file or directory
'''
I'm green to this, how can I deal with it
Thank you

**Comment by Dustone-Mu** [comment]
It's lack of .so file. Make sure that nvcc is in you system's path, then when you rerun the sampler code, those .cu/.h/.c files will be compiled automaticly. If not, plz click here [https://github.com/BoChenGroup/PyDPM/issues/16#issuecomment-1384034217](https://github.com/BoChenGroup/PyDPM/issues/16#issuecomment-1384034217) for reference

**Comment by chaojiewang94** [comment]
solved
