### ISSUE TITLE
Requiests for adding new diffusion models

### ISSUE THREAD

**Issue by NTUDeft** [BoChenGroup/PyDPM#25]
It is great to see u to start to increase the variants of diffusion models. I wonder if you have a plan to include more recent popular diffusion models in your project, just like

Denoising Diffusion Implicit Models. NIPS 2022
Improved Vector Quantized Diffusion Models
. CVPR 2023

These two are widely treated as baselines in today's reseach

Thanks

**Comment by chaojiewang94** [comment]
Thanks for sugestions. We have added these two models in our extension plan.

**Comment by NTUDeft** [comment]
Thanks
