### ISSUE TITLE
how could I use the sampler module to build my own PRNGs?

### ISSUE THREAD

**Issue by optimus20** [BoChenGroup/PyDPM#26]
Thanks for your contributions to the cuda based sampler module. I want to build some new distributions' PRNG by this sampler, and find out there are different files in sampler/_compact. wanna to know where and how to edit them for new PRNG

**Comment by Dustone-Mu** [comment]
You can edit the file in ./sampler/ to build your own PRNG.
/_compact/distribution_sampler_x.cu: build PRNG thread funciton and organize them
/distribution_sampler_x.py:  include the kernel function by dll and retype the input and output, then edit the sampler API.

If have any follow-up questions, you can contact us. And you are welcome to submit your own built PRNGs to PyDPM. We'd appreciate that.
