### ISSUE TITLE
A small bug 

### ISSUE THREAD

**Issue by Fishinginvain** [BoChenGroup/PyDPM#28]
Dear writer, in the PyDPM/pydpm/model/deep_learning_pm/vae.py, attribute sample and forword in class VAE have some bugs (decoder is wrong, where vae_decoder is right) , and now have be checked.
                                                                                                                                                           BuFeng Ge

**Comment by xinyangATK** [comment]
The bug has been fixed.
Thanks for your interest in building our community and welcome for the further questions.

**Comment by xinyangATK** [comment]
This bug has been fixed.
