### ISSUE TITLE
Warning: shape -36.502342 <= 0 in threads idx: 8258 [thread:(2125698480, 0),  block:(66, 0)]

### ISSUE THREAD

**Issue by wds2014** [BoChenGroup/PyDPM#3]
**DPGDS error**
**I meet this warning when running dpgds demo**:
Training Stage:  epoch   0 takes 4.90 seconds. Likelihood:  -0.425
Training Stage:  epoch   1 takes 5.11 seconds. Likelihood:  -0.367
Training Stage:  epoch   2 takes 4.83 seconds. Likelihood:  -0.373
Training Stage:  epoch   3 takes 4.65 seconds. Likelihood:  -0.376
Training Stage:  epoch   4 takes 4.54 seconds. Likelihood:  -0.378
Training Stage:  epoch   5 takes 4.49 seconds. Likelihood:  -0.377
Training Stage:  epoch   6 takes 4.44 seconds. Likelihood:  -0.377
Training Stage:  epoch   7 takes 4.41 seconds. Likelihood:  -0.377
Training Stage:  epoch   8 takes 4.36 seconds. Likelihood:  -0.374
Training Stage:  epoch   9 takes 4.37 seconds. Likelihood:  -0.369
Training Stage:  epoch  10 takes 4.36 seconds. Likelihood:  -0.367
Training Stage:  epoch  11 takes 4.35 seconds. Likelihood:  -0.363
Training Stage:  epoch  12 takes 4.28 seconds. Likelihood:  -0.360
Training Stage:  epoch  13 takes 4.26 seconds. Likelihood:  -0.357
Training Stage:  epoch  14 takes 4.25 seconds. Likelihood:  -0.349
Training Stage:  epoch  15 takes 4.25 seconds. Likelihood:  -0.343
Training Stage:  epoch  16 takes 4.24 seconds. Likelihood:  -0.334
Training Stage:  epoch  17 takes 4.28 seconds. Likelihood:  -0.326
Training Stage:  epoch  18 takes 4.25 seconds. Likelihood:  -0.315
Training Stage:  epoch  19 takes 4.23 seconds. Likelihood:  -0.306
Training Stage:  epoch  20 takes 4.20 seconds. Likelihood:  -0.294
Warning: shape -36.502342 <= 0 in threads idx: 8258 [thread:(2125698480, 0),  block:(66, 0)]
Warning: shape -0.142884 <= 0 in threads idx: 8260 [thread:(2125698480, 0),  block:(68, 0)]
Warning: shape -2.206542 <= 0 in threads idx: 8262 [thread:(2125698480, 0),  block:(70, 0)]
Warning: shape -0.727849 <= 0 in threads idx: 8264 [thread:(2125698480, 0),  block:(72, 0)]
Warning: shape -0.010437 <= 0 in threads idx: 8265 [thread:(2125698480, 0),  block:(73, 0)]
Warning: shape -0.446480 <= 0 in threads idx: 8266 [thread:(2125698480, 0),  block:(74, 0)]
Warning: shape -0.286718 <= 0 in threads idx: 8267 [thread:(2125698480, 0),  block:(75, 0)]

**Comment by chaojiewang94** [comment]
maybe u should check the input of the gamma distribution. 
For these gamma distribuited varibales with shape parameters < 0, the pydpm distribution sampler will output a warining and force the sampling resutls to zeros.
[https://github.com/BoChenGroup/Pydpm/blob/master/pydpm/_sampler/_compact/sampler_kernel_win.cu](url)

Line 41: 
https://github.com/BoChenGroup/Pydpm/blob/master/pydpm/_sampler/_compact/sampler_kernel_win.cu

**Comment by chaojiewang94** [comment]
@wds2014 are u using the the latested version published in Github, the testing of all demos in Github is passed in our PCs. 

If yes, please ask @Dustone-Mu for checking the demo of dpgds

**Comment by chaojiewang94** [comment]
has been solved
