### ISSUE TITLE
Filed installation of pycuda 

### ISSUE THREAD

**Issue by yanhe-Z** [BoChenGroup/PyDPM#4]
I get errors during installing the denpendency of pycuda:
ERROR: Could not build wheels for pycuda, which is required to install pyproject.toml-based projects
 from pycuda._driver import * # noqa
ImportError: DLL load failed: 
Those errors occurred during the installation by pip. I hava changed 2 device to install pydpm, but It doesn't work both : (
The environment of my win PC is as list:
python 3.6
cuda 10.2
win 10

**Comment by Dustone-Mu** [comment]
We have been reminded of the difficult during the installation of pycuda, and the dependency of pycuda has been removed now. You can clone pydpm3.0 in GitHub, and we will push the new version of pydpm to pypi today.

**Comment by chaojiewang94** [comment]
This issue has been sovled and we will release the requirement list in the following version of PyDPM. Welcome for the further questions.
