### ISSUE TITLE
Some questions about dataset used in your demo

### ISSUE THREAD

**Issue by NTUDeft** [BoChenGroup/PyDPM#8]
Hi

 Thanks for your efforts for deep generative models. However, I find that the datasets used in your demos are not public datasets. Can you replace the datasets in your code with those in torchvision/torchtext etc, which will be more convenient for us to extend the models in your libarary.

Thanks

**Comment by chaojiewang94** [comment]
thanks for your suggestion, we have unified the formation and preprocessing procedure of dataset in the demo examples included in our library.

**Comment by chaojiewang94** [comment]
has been solved
